project:
  type: website
  output-dir: _site
  # resources:
  #   - "/docs/download/_download.json"
  #   - "/docs/download/_prerelease.json"
  #   - "/_redirects"
  preview: 
    port: 7777

website:
  title: "Gyanantaran"
  image: "gyanantaran.png"
  favicon: "favicon.png"
  # google-analytics: "G-FV9Z7SDZ0M"
  open-graph: true
  twitter-card: true
  site-url: https://gyanantaran.github.io/quarto-site
  repo-url: https://github.com/gyanantaran/quarto-site
  issue-url: https://github.com/gyanantaran/quarto-site/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  search:
    type: overlay
    # algolia:
    #   index-name: prod_QUARTO
    #   application-id: ZPJB5I1QN7
    #   search-only-api-key: 41be6c1e0a7fea4a51b107810facf577
    #   analytics-events: true
    #   show-logo: true
  page-footer:
    left: |
      Image of the day:
      [![](https://www.nasa.gov/wp-content/themes/nasa/assets/images/nasa-logo.svg){fig-alt="NASA" width=65px}](https://www.nasa.gov/image-of-the-day/)
    center:
      - text: "About"
        href: about.qmd
    right:
      - icon: twitter
        href: https://twitter.com/gyanantaran
        aria-label: Gyanantaran Twitter
      - icon: github
        href: https://github.com/gyanantaran
        aria-label: Gyanantaran GitHub
  navbar:
    background: light
    logo: favicon.png
    logo-alt: "Gyanantaran logo."
    title: false
    collapse-below: lg
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Help"
        menu:
          - text: "Ask a Question"
            icon: "chat-right-text"
            href: "https://github.com/gyanantaran/quarto-site/discussions"
    tools:
      - icon: twitter
        href: https://twitter.com/gyanantaran
        text: Gyanantaran Twitter
      - icon: github
        href: https://github.com/gyanantaran
        text: Gyanantaran GitHub


# bibliography: references.bib

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    include-after-body: js.html
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px


# filters:
#   - filters/tools-tabset.lua


# freeze: true

# editor: visual

# profile:
#   group: 
#     - [rc,prerelease]
